# Generated by Django 6.0.6 on 2026-06-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchase_is_paid_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchased_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
