# Generated by Django 6.0.6 on 2026-06-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_category_remove_product_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='purchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
