# Generated by Django 6.0.6 on 2026-06-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_file_remove_purchase_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
