# Generated by Django 6.0.6 on 2026-06-15 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_purchase_is_active_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
